// frontend/src/mockGames.js

export const mockGames = [
  {
    id: "1",
    title: "Spiderman",
    description: "Developed by Insomniac Games in collaboration with Marvel, and optimized for PC by Nixxes Software, Marvel's Spider-Man Remastered on PC introduces an experienced Peter Parker who’s fighting big crime and iconic villains in Marvel’s New York.",
    price: 59.99,
    genres: "Action, Adventure",
    platforms: "PC, PS5",
    coverUrl: "/img/spiderman.jpg",
    sysreqMin: "Windows 10, i5, 8GB RAM, GTX 1060",
  },
  {
    id: "2",
    title: "God of War: Ragnarok",
    description: "THE NORSE SAGA CONTINUES From Santa Monica Studio and brought to PC in partnership with Jetpack Interactive comes God of War Ragnarök, an epic and heartfelt journey that follows Kratos and Atreus as they struggle with holding on and letting go.",
    price: 69.99,
    genres: "Action, RPG",
    platforms: "PS5",
    coverUrl: "/img/gow_ragnarok.jpg",
    sysreqMin: "PS5 only",
  },
  {
    id: "3",
    title: "Spiderman: Miles Morales",
    description: "Following the events of Marvel’s Spider-Man Remastered, teenager Miles Morales is adjusting to his new home while following in the footsteps of his mentor, Peter Parker, as a new Spider-Man. But when a fierce power struggle threatens to destroy his new home, Miles realizes that with great power, there must also come great responsibility.",
    price: 49.99,
    genres: "Action, Adventure",
    platforms: "PC, PS5",
    coverUrl: "/img/miles_morales.jpg",
    sysreqMin: "Windows 10, i5, 8GB RAM, GTX 1070",
  },
  {
    id: "4",
    title: "Stray",
    description: "Lost, alone and separated from family, a stray cat must untangle an ancient mystery to escape a long-forgotten city.",
    price: 29.99,
    genres: "Adventure, Indie",
    platforms: "PC, PS5",
    coverUrl: "/img/stray.jpg",
    sysreqMin: "Windows 10, i5, 8GB RAM, GTX 1050",
  },
  {
    id: "5",
    title: "NBA 2K25",
    description: "Command every court with authenticity and realism Powered by ProPLAY™, giving you ultimate control over how you play in NBA 2K25. Define your legacy in MyCAREER, MyTEAM, MyNBA, and The W. Express yourself with an array of customization options and explore new ways to play.",
    price: 59.99,
    genres: "Sports, Simulation",
    platforms: "PC, PS5, Xbox",
    coverUrl: "/img/nba2k25.jpg",
    sysreqMin: "Windows 10, i7, 16GB RAM, RTX 2060",
  },
  {
    id: "6",
    title: "Cyberpunk 2077",
    description: "Cyberpunk 2077 is an open-world, action-adventure RPG set in the megalopolis of Night City, where you play as a cyberpunk mercenary wrapped up in a do-or-die fight for survival. Improved and featuring all-new free additional content, customize your character and playstyle as you take on jobs, build a reputation, and unlock upgrades.",
    price: 39.99,
    genres: "RPG, Action",
    platforms: "PC, PS5, Xbox",
    coverUrl: "/img/cyberpunk2077.jpg",
    sysreqMin: "Windows 10, i7, 12GB RAM, GTX 1660",
  },
  {
    id: "7",
    title: "Kingdom Come: Deliverance II",
    description: "A thrilling story-driven action RPG, with a rich open world, set in 15th century Medieval Europe. Experience the ultimate medieval adventure - through the eyes of young Henry - as you embark on a journey of epic proportions.",
    price: 49.99,
    genres: "RPG, Action, Historical",
    platforms: "PC, PS5, Xbox",
    coverUrl: "/img/kingdom_come.jpg",
    sysreqMin: "Windows 10, i7, 16GB RAM, GTX 1660 or better",
  },
  {
    id: "8",
    title: "Dark Souls Remastered",
    description: "Then, there was fire. Re-experience the critically acclaimed, genre-defining game that started it all. Beautifully remastered, return to Lordran in stunning high-definition detail running at 60fps.",
    price: 39.99,
    genres: "Action, RPG, Souls-like",
    platforms: "PC, PS4, Xbox, Switch",
    coverUrl: "/img/dark_souls_remastered.jpg",
    sysreqMin: "Windows 10, i5, 8GB RAM, GTX 660 or better",
  },
];